name: "Jenkins X CI workflow macos"


on:
  push:
    branches: [ test ]



jobs:

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#using-a-specific-python-version
  build-python-macos-latest:
    name: "Jenkins X macos-latest - macos-latest 10.15.7"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: "Install Jenkins X"
      run: |
        brew tap jenkins-x/jx 
        brew install jx
        #brew install kops    
        jx version    

