name: "Jenkins X CI workflow windows"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month      




jobs:

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#using-a-specific-python-version
  build-python-windows-latest:
    name: "Jenkins X windows-latest"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    # You can test your matrix by printing the current Python version
    - name: "Install Jenkins X"
      run: |
        choco install jenkins-x
        choco upgrade jenkins-x
        jx version         

          