name: "minikube jenkins X CI workflow ubuntu"


on:
  push:
    branches: [ test ]


jobs:

  build-ubuntu-latest-job:
    name: "minikube Jenkins X  on ubuntu-latest - ubuntu 18.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
          echo "===================================================================================="
                        hostnamectl status
          echo "===================================================================================="
          echo "         \   ^__^                                                                  "
          echo "          \  (oo)\_______                                                          "
          echo "             (__)\       )\/\                                                      "
          echo "                 ||----w |                                                         "
          echo "                 ||     ||                                                         "
          echo "===================================================================================="           
    # https://jenkins-x.io/v3/admin/platforms/minikube/    
    - name: "deploy jenkins-x minikube"
      run: |
        #delete the current cluster
        minikube delete 
        #create a minikube cluster
        # X Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/
        # minikube start --cpus 4 --memory 8048 --disk-size=100g --addons=ingress --vm=true          
        # Requested cpu count 4 is greater than the available cpus of 2
        # X Exiting due to RSRC_OVER_ALLOC_MEM: Requested memory allocation 8048MB is more than your system limit 6953MB.
        minikube start --driver=docker --cpus 2 --memory 6952 --disk-size=100g --addons=ingress --vm=true 
        minikube version --short
        minikube version --components

  ubuntu-2004-job:
    name: "minikube Jenkins X on ubuntu-20.04"
    runs-on: ubuntu-20.04   
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
          echo "===================================================================================="
                        hostnamectl status
          echo "===================================================================================="
          echo "         \   ^__^                                                                  "
          echo "          \  (oo)\_______                                                          "
          echo "             (__)\       )\/\                                                      "
          echo "                 ||----w |                                                         "
          echo "                 ||     ||                                                         "
          echo "===================================================================================="           
    # https://jenkins-x.io/v3/admin/platforms/minikube/    
    - name: "deploy jenkins-x minikube"
      run: |
        #delete the current cluster
        minikube delete 
        #create a minikube cluster
        # X Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/
        # minikube start --cpus 4 --memory 8048 --disk-size=100g --addons=ingress --vm=true          
        # Requested cpu count 4 is greater than the available cpus of 2
        # X Exiting due to RSRC_OVER_ALLOC_MEM: Requested memory allocation 8048MB is more than your system limit 6953MB.
        minikube start --driver=docker --cpus 2 --memory 6952 --disk-size=100g --addons=ingress --vm=true 
        minikube version --short
        minikube version --components


  build-ubuntu-1804-job:
    name: "Jenkins X  on ubuntu 18.04"
    runs-on: ubuntu-18.04 # 18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
          echo "===================================================================================="
                        hostnamectl status
          echo "===================================================================================="
          echo "         \   ^__^                                                                  "
          echo "          \  (oo)\_______                                                          "
          echo "             (__)\       )\/\                                                      "
          echo "                 ||----w |                                                         "
          echo "                 ||     ||                                                         "
          echo "===================================================================================="           
    # https://jenkins-x.io/v3/admin/platforms/minikube/    
    - name: "deploy jenkins-x"
      run: |
        #delete the current cluster
        minikube delete 
        #create a minikube cluster
        # X Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/
        # minikube start --cpus 4 --memory 8048 --disk-size=100g --addons=ingress --vm=true          
        # Requested cpu count 4 is greater than the available cpus of 2
        # X Exiting due to RSRC_OVER_ALLOC_MEM: Requested memory allocation 8048MB is more than your system limit 6953MB.
        minikube start --driver=docker --cpus 2 --memory 6952 --disk-size=100g --addons=ingress --vm=true 
        minikube version --short
        minikube version --components

  # ubuntu-1604-job:
  #   name: "Jenkins X on ubuntu-16.04"
  #   runs-on: ubuntu-16.04   
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status         
  #   - uses: actions/checkout@v2
  #   - name: "Install Jenkins X"
  #     run: |
  #       mkdir -p ~/.jx/bin
  #       curl -L "https://github.com/jenkins-x/jx/releases/download/$(curl --silent "https://github.com/jenkins-x/jx/releases/latest" | sed 's#.*tag/\(.*\)\".*#\1#')/jx-linux-amd64.tar.gz" | tar xzv -C ~/.jx/bin
  #       export PATH=$PATH:~/.jx/bin
  #       echo 'export PATH=$PATH:~/.jx/bin' >> ~/.bashrc
  #       jx version

