name: "Jenkins X CI workflow ubuntu"


on:
  push:
    branches: [ dev ]


jobs:

  build-ubuntu-latest-job:
    name: "PJenkins X  on ubuntu-latest - ubuntu 18.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Python 3.8"
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: "Install Jenkins X"
      run: |
        curl -L "https://github.com/jenkins-x/jx/releases/download/$(curl --silent https://api.github.com/repos/jenkins-x/jx/releases/latest | jq -r '.tag_name')/jx-linux-amd64.tar.gz" | tar xzv "jx"


  build-ubuntu-1804-job:
    name: "Jenkins X  on ubuntu 18.04"
    runs-on: ubuntu-18.04 # 18.04
    steps:
    - uses: actions/checkout@v2
    - name: "Install Jenkins X"
      run: |
        mkdir -p ~/.jx/bin
        curl -L "https://github.com/jenkins-x/jx/releases/download/$(curl --silent "https://github.com/jenkins-x/jx/releases/latest" | sed 's#.*tag/\(.*\)\".*#\1#')/jx-linux-amd64.tar.gz" | tar xzv -C ~/.jx/bin
        export PATH=$PATH:~/.jx/bin
        echo 'export PATH=$PATH:~/.jx/bin' >> ~/.bashrc
        jx --version
    - name: "Install Jenkins X if jq not installed"
      run: |
        curl -L "https://github.com/jenkins-x/jx/releases/download/$(curl --silent "https://github.com/jenkins-x/jx/releases/latest" | sed 's#.*tag/(.*)\".*#1#')/jx-linux-amd64.tar.gz" | tar xzv "jx"

  ubuntu-1604-job:
    name: "Jenkins X on ubuntu-16.04"
    runs-on: ubuntu-16.04   
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status         
    - uses: actions/checkout@v2
    - name: "Install Jenkins X"
      run: |
        curl -L "https://github.com/jenkins-x/jx/releases/download/$(curl --silent https://api.github.com/repos/jenkins-x/jx/releases/latest | jq -r '.tag_name')/jx-linux-amd64.tar.gz" | tar xzv "jx"

     

  ubuntu-2004-job:
    name: "Jenkins X on ubuntu-20.04"
    runs-on: ubuntu-20.04   
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status         
    - uses: actions/checkout@v2
    - name: "Install Jenkins X"
      run: |
        curl -L "https://github.com/jenkins-x/jx/releases/download/$(curl --silent https://api.github.com/repos/jenkins-x/jx/releases/latest | jq -r '.tag_name')/jx-linux-amd64.tar.gz" | tar xzv "jx"

        